# Shell variables
# Generated by 'wal'
wallpaper='/home/ricky/Pictures/Wallpapers/solar_canyon.jpg'

# Special
background='#070F25'
foreground='#c6ddc7'
cursor='#c6ddc7'

# Colors
color0='#070F25'
color1='#EE574D'
color2='#FC9637'
color3='#F9A44E'
color4='#F6D262'
color5='#22718E'
color6='#4EA0AA'
color7='#c6ddc7'
color8='#8a9a8b'
color9='#EE574D'
color10='#FC9637'
color11='#F9A44E'
color12='#F6D262'
color13='#22718E'
color14='#4EA0AA'
color15='#c6ddc7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
